# network architecture
# encoder related
etype: blstmp # encoder architecture type
elayers: 4
eunits: 256
eprojs: 256
subsample: "1_2_2_2" # skip every n frame from input to nth layers
# decoder related
dlayers: 1
dunits: 256
# attention related
atype: location
aconv-chans: 10
aconv-filts: 100

# hybrid CTC/attention
mtlalpha: 0.2

# minibatch related
batch-size: 30
maxlen-in: 800  # if input length  > maxlen_in, batchsize is automatically reduced
maxlen-out: 150 # if output length > maxlen_out, batchsize is automatically reduced

# optimization related
sortagrad: 0 # Feed samples from shortest to longest ; -1: enabled for all epochs, 0: disabled, other: enabled for 'other' epochs
opt: adadelta
epochs: 15
patience: 3

# embed_dim: 256
lm-weight: 0.2

# scheduled sampling option
sampling-probability: 0.1
